# Generated by Django 3.0.4 on 2020-03-20 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeatMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.IntegerField()),
                ('lat', models.CharField(max_length=32)),
                ('lng', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 20, 8, 31, 8, 756208))),
                ('active', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MarkUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorder', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=128)),
                ('patientId', models.CharField(max_length=32)),
                ('patientStart', models.DateTimeField(default=None)),
                ('patientEnd', models.DateTimeField(default=None)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2020, 3, 20, 8, 31, 8, 793000))),
                ('active', models.IntegerField(default=0)),
            ],
        ),
    ]
