# Generated by Django 3.0.4 on 2020-03-21 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdSourceMap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 6, 31, 37, 119755)),
        ),
        migrations.AlterField(
            model_name='markup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 6, 31, 37, 283236)),
        ),
    ]
