# Generated by Django 3.0.4 on 2020-03-21 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdSourceMap', '0002_auto_20200321_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmap',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 13, 40, 22, 878019)),
        ),
        migrations.AlterField(
            model_name='markup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 13, 40, 23, 93066)),
        ),
    ]
