# Generated by Django 3.0.4 on 2020-03-19 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdSourceMap', '0002_auto_20200319_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmap',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 21, 43, 662810)),
        ),
        migrations.AlterField(
            model_name='markup',
            name='patientEnd',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='markup',
            name='patientStart',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='markup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 21, 43, 700717)),
        ),
    ]
