# Generated by Django 3.0.4 on 2020-03-19 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdSourceMap', '0004_auto_20200319_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatmap',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 34, 15, 968376)),
        ),
        migrations.AlterField(
            model_name='markup',
            name='patientId',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='markup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 34, 16, 17280)),
        ),
    ]
