# Generated by Django 3.0.4 on 2020-03-19 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdSourceMap', '0005_auto_20200319_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatmap',
            name='active',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 38, 22, 490501)),
        ),
        migrations.AlterField(
            model_name='markup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 18, 38, 22, 531859)),
        ),
    ]
